[workspace]
resolver = "2"
members = ["S00_hello_world", "S01_variables", "S02_vectors", "S03_strings", "S04_functions", "S05_control_flows", "S06_ownership", "S07_structs", "S08_lifetimes", "S09_enums", "S10_pattern_matching", "S99_questions"]
